config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'people#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  
  # def alive(:alive)
  #   if alive=true
  #     puts 'Yes'
  #   else
  #     puts 'No'
  #   end
  # end

  # def full_name(name)
  #   @full_name = 
  # end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit,:update,:destroy]
  def index
    @people = Person.all
  end

  def show
   
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)
 
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    # @person = Person.find(params[:id])
  end

  def update
  
    if @person.update(people_params)
      redirect_to person_path
    else
      render :edit
    end
  end

  def destroy
  
    redirect_to pages_path
  end

  private

   def people_params
     params.require(:person).permit(:first_name, :last_name, :age,:hair_color,:eye_color,:gender,:alive)
   end

   def set_person
    @person = Person.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_ template.html.erb
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br />
  <%= f.label :age %>
  <%= f.text_field :age %>
<br />
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
<br />
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
<br />
  <%= f.label :gender %>
  <%= f.text_field :gender %>
<br />
  <%= f.label :alive %>
  <%= f.check_box :alive %>
<br />
  <%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br />
  <%= f.label :age %>
  <%= f.text_field :age %>
<br />
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
<br />
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
<br />
  <%= f.label :gender %>
  <%= f.text_field :gender %>
<br />
  <%= f.label :alive %>
  <%= f.check_box :alive %>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1> People </h1>
<% @people.each do |person| %>
  <h2><%= person.first_name%> <%= person.last_name%> </h2>
  <%= link_to 'Show Person', person_path(person) %>
  <%= link_to 'Edit Person', edit_person_path(person) %>
  <%= link_to 'Delete Person', person, method: :delete %>
<% end %>
<h1> Creat New Person </h1>
<p><%= link_to 'New Person', new_person_path %></p>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br />
  <%= f.label :age %>
  <%= f.text_field :age %>
<br />
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
<br />
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
<br />
  <%= f.label :gender %>
  <%= f.text_field :gender %>
<br />
  <%= f.label :alive %>
  <%= f.check_box :alive %>
<br />
  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>People</h1>
<h1><%= @person.first_name %> <%= @person.last_name %></h1>
<p>Age: <%= @person.age %></p>
<p>Hair color: <%= @person.hair_color%></p>
<p>Eye color: <%= @person.eye_color%></p>
<p>Gender: <%= @person.gender%></p>
<p>Alive: <%= @person.alive%></p>

<%= link_to 'Back', people_path %>